#!/usr/bin/env bash
set -eu

if command -v systemctl >/dev/null 2>&1; then
  systemctl daemon-reload || true
fi

if command -v udevadm >/dev/null 2>&1; then
  udevadm control --reload-rules || true
  udevadm trigger || true
fi
