import Foundation

enum GlassToKeyDefaultsKeys {
    static let leftDeviceID = "GlassToKey.leftDeviceID"
    static let rightDeviceID = "GlassToKey.rightDeviceID"
    static let columnSettings = "GlassToKey.columnSettings"
    static let customButtons = "GlassToKey.customButtons"
    static let keyMappings = "GlassToKey.keyMappings"
    static let tapHoldDuration = "GlassToKey.tapHoldDuration"
    static let dragCancelDistance = "GlassToKey.dragCancelDistance"
    static let forceClickMin = "GlassToKey.forceClickMin"
    static let forceClickCap = "GlassToKey.forceClickCap"
    static let hapticStrength = "GlassToKey.hapticStrength"
    static let typingGraceMs = "GlassToKey.typingGraceMs"
    static let intentMoveThresholdMm = "GlassToKey.intentMoveThresholdMm"
    static let intentVelocityThresholdMmPerSec = "GlassToKey.intentVelocityThresholdMmPerSec"
    static let tapClickCadenceMs = "GlassToKey.twoFingerClickCadenceMs"
    static let layoutPreset = "GlassToKey.layoutPreset"
    static let autoResyncMissingTrackpads = "GlassToKey.autoResyncMissingTrackpads"
    static let autocorrectEnabled = "GlassToKey.autocorrectEnabled"
    static let snapRadiusPercent = "GlassToKey.snapRadiusPercent"
    static let chordalShiftEnabled = "GlassToKey.chordalShiftEnabled"
    static let keyboardModeEnabled = "GlassToKey.keyboardModeEnabled"
    static let runAtStartupEnabled = "GlassToKey.runAtStartupEnabled"
    static let twoFingerTapGestureAction = "GlassToKey.twoFingerTapGestureAction"
    static let threeFingerTapGestureAction = "GlassToKey.threeFingerTapGestureAction"
    static let fourFingerHoldGestureAction = "GlassToKey.fourFingerHoldGestureAction"
    static let fiveFingerSwipeLeftGestureAction = "GlassToKey.fiveFingerSwipeLeftGestureAction"
    static let fiveFingerSwipeRightGestureAction = "GlassToKey.fiveFingerSwipeRightGestureAction"
}
