namespace GlassToKey;

public readonly record struct TouchProcessorRuntimeSnapshot(
    int ActiveLayer,
    bool MomentaryLayerActive,
    bool TypingEnabled,
    bool KeyboardModeEnabled,
    int ContactCount,
    int LeftContacts,
    int RightContacts,
    int LastFrameLeftContacts = 0,
    int LastFrameRightContacts = 0,
    int LastRawLeftContacts = 0,
    int LastRawRightContacts = 0,
    int LastOnKeyLeftContacts = 0,
    int LastOnKeyRightContacts = 0,
    bool LastChordSuppressedLeft = false,
    bool LastChordSuppressedRight = false,
    int TouchStateCount = 0,
    int IntentTouchStateCount = 0,
    bool GesturePriorityLeft = false,
    bool GesturePriorityRight = false,
    bool ChordShiftLeft = false,
    bool ChordShiftRight = false,
    string IntentMode = "Idle",
    long FramesProcessed = 0,
    long QueueDrops = 0,
    long StaleTouchExpirations = 0,
    long ReleaseDroppedTotal = 0,
    long ReleaseDroppedGesturePriority = 0,
    long LastReleaseDroppedTicks = 0,
    string LastReleaseDroppedReason = "",
    long DispatchEnqueued = 0,
    long DispatchSuppressedTypingDisabled = 0,
    long DispatchSuppressedRingFull = 0,
    int DispatchQueueCount = 0,
    long DispatchQueueDrops = 0,
    bool DispatchPumpAlive = false,
    long DispatchPumpDispatchCalls = 0,
    long DispatchPumpTickCalls = 0,
    long DispatchPumpLastDispatchTicks = 0,
    long DispatchPumpLastTickTicks = 0,
    long DispatchPumpLastFaultTicks = 0,
    string DispatchPumpLastFault = "",
    long DispatcherDispatchCalls = 0,
    long DispatcherTickCalls = 0,
    long DispatcherSendFailures = 0,
    int DispatcherActiveRepeats = 0,
    int DispatcherKeysDown = 0,
    int DispatcherActiveModifiers = 0,
    long DispatcherLastDispatchTicks = 0,
    long DispatcherLastTickTicks = 0,
    string DispatcherLastError = "");
